{% set name = "colcon-bash" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colcon-bash-{{ version }}.tar.gz
  sha256: 29a223a66828e18aad9b8db5087f7114e388601830091830ca17b095ada2cbac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colcon-core >=0.4.0
    - python >=3.6

test:
  imports:
    - colcon_bash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to provide Bash scripts.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-rivero
    - Tobias-Fischer
